CREATE TABLE "VBS_FLOW" 
   (   "ID" NUMBER(*,0) NOT NULL ENABLE, 
       "FLOW_ID" VARCHAR2(256) NOT NULL ENABLE, 
       "DATE_TREATMENT" TIMESTAMP (6) NOT NULL ENABLE, 
       "LAST_UPDATE" TIMESTAMP (6) NOT NULL ENABLE, 
       "SITE_CD" VARCHAR2(12), 
       "ID_ROOT" NUMBER(*,0), 
       "DOC_NBR" NUMBER(*,0), 
       "SPLIT_PART" NUMBER(*,0), 
       "SPLIT_TOTAL" NUMBER(*,0), 
       "VERSION" NUMBER, 
       "FLOWREF" VARCHAR2(42), 
	   
        CONSTRAINT "PK_VBS_FLOW" PRIMARY KEY ("ID") ENABLE
   ) ;
   COMMENT ON COLUMN "VBS_FLOW"."DATE_TREATMENT" IS 'date de traitement';
   COMMENT ON COLUMN "VBS_FLOW"."LAST_UPDATE" IS 'last update of the flow';
   COMMENT ON COLUMN "VBS_FLOW"."SITE_CD" IS 'site code';
   COMMENT ON COLUMN "VBS_FLOW"."DOC_NBR" IS 'nombre de coument';
   COMMENT ON COLUMN "VBS_FLOW"."SPLIT_PART" IS 'Index d''un flux de control';
   COMMENT ON COLUMN "VBS_FLOW"."SPLIT_TOTAL" IS 'Nombre total de flux attendu';
  

 

CREATE TABLE "VBS_FLOW_UNIT" 
   (   "FLOW_UNIT_ID" NUMBER(*,0) NOT NULL ENABLE, 
       "VBS_DIFFUSION_ID_DIFFUSION" NUMBER(*,0), 
       "VBS_FLOW_ID" NUMBER(*,0), 
       "DATE_TREATMENT" TIMESTAMP (6), 
       "SITE_CD" VARCHAR2(12), 
       "CHK_SUM" VARCHAR2(256), 
       "GEN_START" TIMESTAMP (6), 
       "GEN_END" TIMESTAMP (6), 
       "APP_START" TIMESTAMP (6), 
       "APP_END" TIMESTAMP (6), 
       "APP_VALIDATE_DATE" TIMESTAMP (6), 
       "APP_MODE" VARCHAR2(12), 
       "APP_STATUS" VARCHAR2(16), 
       "APP_DSC" VARCHAR2(2000), 
       "APP_USR_VBS_ID" VARCHAR2(32), 
       "APP_USR_NME" VARCHAR2(128), 
       "APP_USR_LSTNME" VARCHAR2(128), 
       "DOC_TYPE" VARCHAR2(16), 
       "DOC_NME" VARCHAR2(256), 
       "DOC_NME_OLIS" VARCHAR2(256), 
       "DOC_NBR_PAGE" NUMBER(*,0), 
       "FUND_CD" VARCHAR2(32), 
       "TANS_NBR" NUMBER(32,0), 
       "NAV_DATE" TIMESTAMP (6), 
       "VAL_START" DATE, 
       "VAL_END" DATE, 
       "EXE_DATE" DATE, 
       "INVESTOR_ID" NUMBER(32,0), 
       "INVESTOR_NME" VARCHAR2(256), 
       "DIST_ACC_ID" NUMBER(32,0), 
       "DIST_NME" VARCHAR2(256), 
       "GED_ID" VARCHAR2(50), 
       "DOC_LENGTH" NUMBER(*,0), 
       "FUND_NME" VARCHAR2(256), 
       "DOC_DTE_TRADE" DATE, 
       "INVESTOR_PARTICIPANT" VARCHAR2(256), 
       "INVESTOR_STA_GRP_CDE" VARCHAR2(30), 
       "INVESTOR_LANGUAGE" VARCHAR2(4), 
       "INVESTOR_CURRENCY" VARCHAR2(4), 
       "DOC_HEADER_VALUATIONDATE" DATE, 
       "DOC_ISSUE_DATE" DATE, 
       "DOC_STA_NUMBER" VARCHAR2(20), 
       "DOC_CONTACT_ADD1" VARCHAR2(256), 
       "DOC_CONTACT_ADD2" VARCHAR2(256), 
       "DOC_CONTACT_ADD3" VARCHAR2(256), 
       "DOC_CONTACT_ADD4" VARCHAR2(256), 
       "DOC_CONTACT_ADD5" VARCHAR2(256), 
       "DOC_CONTACT_ADD6" VARCHAR2(256), 
       "DOC_CONTACT_ADD7" VARCHAR2(256), 
       "DOC_CONTACT_ADD8" VARCHAR2(256), 
       "DOC_REF" VARCHAR2(64), 
       "DOC_VBS_ID" VARCHAR2(320), 
       "INVESTOR_ACC_ID" VARCHAR2(320), 
       "DOC_UNIT_XML" CLOB, 
       "TRN_REF" VARCHAR2(50), 
	   
        CONSTRAINT "PK_VBS_FLOW_UNIT" PRIMARY KEY ("FLOW_UNIT_ID") ENABLE
   );
  
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."SITE_CD" IS 'site code';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."CHK_SUM" IS 'checksum du pdf';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."GEN_START" IS 'generation start';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."GEN_END" IS 'generation end';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_START" IS 'date de debut';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_END" IS 'date de fin';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_VALIDATE_DATE" IS 'date approval';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_MODE" IS 'mode d''approbation';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_STATUS" IS 'status de l approbation';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_DSC" IS 'description du rejet';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_USR_VBS_ID" IS 'id du user vbs';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_USR_NME" IS 'user name';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."APP_USR_LSTNME" IS 'lastname';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."DOC_TYPE" IS 'type de document';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."DOC_NME" IS 'nom du fichier pdf concaten2 VBS pr2sent2 sur le portail';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."DOC_NME_OLIS" IS 'Nom du coument unitaire olis example VBSGENERATIONxxxx.xml';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."DOC_NBR_PAGE" IS 'nombre de pages';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."FUND_CD" IS 'fund code';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."TANS_NBR" IS 'transaction number';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."NAV_DATE" IS 'nav date';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."VAL_START" IS 'valuation start date';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."VAL_END" IS 'valuation end date';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."EXE_DATE" IS 'execution date';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."INVESTOR_NME" IS 'investor name';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."DIST_ACC_ID" IS 'distributor account id';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."DIST_NME" IS 'distributor name';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."GED_ID" IS 'GED document ID';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."DOC_LENGTH" IS 'Length du docuement en octet';
   COMMENT ON COLUMN "VBS_FLOW_UNIT"."FUND_NME" IS 'Nom du fond';
   COMMENT ON TABLE "VBS_FLOW_UNIT"  IS 'table des flux unitaire vbs ';
 

CREATE TABLE "VBS_FLOW_UNIT_DIFFUSION" 
   (   "ID" NUMBER(*,0) NOT NULL ENABLE, 
       "FLOW_UNIT_ID" NUMBER(*,0) NOT NULL ENABLE, 
       "ID_DIFFUSION" NUMBER(*,0) NOT NULL ENABLE, 
	   
        CONSTRAINT "PK_VBS_FLOW_UNIT_DIFFUSION" PRIMARY KEY ("ID") ENABLE
   ) ;
  
   COMMENT ON COLUMN "VBS_FLOW_UNIT_DIFFUSION"."FLOW_UNIT_ID" IS 'id du document';
   COMMENT ON COLUMN "VBS_FLOW_UNIT_DIFFUSION"."ID_DIFFUSION" IS 'id de la diffusion';
   COMMENT ON TABLE "VBS_FLOW_UNIT_DIFFUSION"  IS 'Table de mapping entre les documents VB_FLOW_UNIT et les diffusion VBS_DIFFUSION';

 

CREATE TABLE "VBS_FLOW_UNIT_MEDIA" 
   (   "ID_MEDIA" NUMBER(*,0) NOT NULL ENABLE, 
       "VBS_FLOW_UNIT_FLOW_UNIT_ID" NUMBER(*,0) NOT NULL ENABLE, 
       "MEDIA_CD" VARCHAR2(4), 
        
		CONSTRAINT "PK_VBS_FLOW_UNIT_MEDIA" PRIMARY KEY ("ID_MEDIA") ENABLE
   ) ;
 
  
   COMMENT ON TABLE "VBS_FLOW_UNIT_MEDIA"  IS 'type de media (pour la diffussion ) donc
MAL mail
FAX fax
PAP papier';


 

CREATE TABLE "VBS_FLOW_UNIT_SUB_FND" 
   (   "ID_SUB_FND" NUMBER(*,0) NOT NULL ENABLE, 
       "VBS_FLOW_UNIT_FLOW_UNIT_ID" NUMBER(*,0) NOT NULL ENABLE, 
       "SUB_FND_CD" VARCHAR2(48) NOT NULL ENABLE, 
       "SUB_FND_NME" VARCHAR2(256) NOT NULL ENABLE, 
       "SUB_FND_ISIN" VARCHAR2(48), 
       "SUB_FND_SHARE_CURRENCY" VARCHAR2(4), 
       "SUB_FND_SHARE_TYPE" VARCHAR2(24), 
       "SUB_FND_ISSUE_FORM" VARCHAR2(24), 
       "SUB_FND_SUB_FND_NAME" VARCHAR2(256), 
       "SUB_FND_FND_REF" VARCHAR2(24), 
       "SUB_FND_FND_NME" VARCHAR2(256), 
       "SUB_FND_SDG_REF" VARCHAR2(12), 
       "SUB_FND_SDG_NAME" VARCHAR2(256), 
       "OPENING_DATE" DATE, 
       "OPENING_UNITS" VARCHAR2(24), 
       "CLOSING_DATE" DATE, 
       "CLOSING_UNITS" VARCHAR2(24), 
	   
        CONSTRAINT "PK_VBS_FLOW_UNIT_SUB_FND" PRIMARY KEY ("ID_SUB_FND") ENABLE
   ) ;
  
   COMMENT ON COLUMN "VBS_FLOW_UNIT_SUB_FND"."SUB_FND_CD" IS 'sub fund code';
   COMMENT ON COLUMN "VBS_FLOW_UNIT_SUB_FND"."SUB_FND_NME" IS 'sub fund name';
   COMMENT ON COLUMN "VBS_FLOW_UNIT_SUB_FND"."SUB_FND_ISIN" IS 'sub fund ISIN';
   COMMENT ON TABLE "VBS_FLOW_UNIT_SUB_FND"  IS 'sous found';
 
CREATE TABLE "VBS_FLOW_UNIT_TRANS" 
   (   "ID_TRANS" NUMBER NOT NULL ENABLE, 
       "VBS_FLOW_UNIT_FLOW_UNIT_ID" NUMBER NOT NULL ENABLE, 
       "TRANSACTION" VARCHAR2(42), 
	   
        CONSTRAINT "PK_VBS_FLOW_UNIT_TRANS" PRIMARY KEY ("ID_TRANS") ENABLE
   ) ;
  
   COMMENT ON TABLE "VBS_FLOW_UNIT_TRANS"  IS 'table contenant les transaction number pour un document donnee';
 
 

CREATE TABLE "VBS_STATUS" 
   (   "ID_STATUS" NUMBER(*,0) NOT NULL ENABLE, 
       "FLOW_ID" VARCHAR2(256) NOT NULL ENABLE, 
       "ID_VBS_FLOW" NUMBER(*,0) NOT NULL ENABLE, 
       "STATUS" VARCHAR2(32), 
       "ID_VBS_DIFF" NUMBER(*,0), 
       "ID_VBS_FLOW_UNIT" NUMBER(*,0), 
       "CREATE_DATE" TIMESTAMP (6), 
       "ERROR_CD" NUMBER(*,0), 
       "ERROR_DESC" VARCHAR2(2048), 
       "ERROR_COUNT" NUMBER(*,0), 
	   
        CONSTRAINT "PK_VBS_STATUS" PRIMARY KEY ("ID_STATUS") ENABLE
   ) ;
 
   COMMENT ON COLUMN "VBS_STATUS"."FLOW_ID" IS 'unique name of the flow';
   COMMENT ON COLUMN "VBS_STATUS"."ID_VBS_FLOW" IS 'ref of the flow in vbs_flow';
   COMMENT ON COLUMN "VBS_STATUS"."ID_VBS_DIFF" IS 'ref of the id difussion (not mandatory)';
   COMMENT ON COLUMN "VBS_STATUS"."ID_VBS_FLOW_UNIT" IS 'ref of the unit doc';

 

CREATE TABLE "VBS_DIFFUSION" 
   (   "ID_DIFFUSION" NUMBER(*,0) NOT NULL ENABLE, 
       "DATE_TREATMENT" TIMESTAMP (6), 
       "DOC_GRP_NBR_PAGE" NUMBER(*,0), 
       "DIFFUSION_TYPE" VARCHAR2(4), 
       "DIFFUSION_ADR" VARCHAR2(768), 
       "DOC_LOCALE" VARCHAR2(32), 
       "DIFFUSION_MODE" VARCHAR2(32), 
       "SITE_CDE" VARCHAR2(6), 
       "IT_REF" VARCHAR2(64), 
       "DFU_LOG_GRP_IDE" VARCHAR2(32), 
       "MGT_CDE" VARCHAR2(5), 
       "OLD_DIFFUSION" NUMBER(*,0), 
       "SPLIT_INDEX" NUMBER(*,0), 
       "SPLIT_TOTAL" NUMBER(*,0), 
       "RE_DFU_LOGR_GRP_IDE" VARCHAR2(32), 
       "PRINT_COLOR" VARCHAR2(12), 
       "ADRESS_NUMBER" VARCHAR2(12), 
       "OFFICIAL_NAME" VARCHAR2(128), 
       "DIFFUSION_XML" CLOB, 
	   
        CONSTRAINT "PK_VBS_DIFFUSION" PRIMARY KEY ("ID_DIFFUSION") ENABLE
   ) ;
  
   COMMENT ON COLUMN "VBS_DIFFUSION"."DATE_TREATMENT" IS 'date de traitement';
   COMMENT ON COLUMN "VBS_DIFFUSION"."DOC_GRP_NBR_PAGE" IS 'nombre de page du document groupe';
   COMMENT ON COLUMN "VBS_DIFFUSION"."DIFFUSION_TYPE" IS 'type de diffusion (MAI ou FAX)';
   COMMENT ON COLUMN "VBS_DIFFUSION"."DIFFUSION_ADR" IS 'Addresse de diffusion (mail ou numero de fax)';
   COMMENT ON COLUMN "VBS_DIFFUSION"."DOC_LOCALE" IS 'language du document';
   COMMENT ON COLUMN "VBS_DIFFUSION"."DIFFUSION_MODE" IS 'type de diffussion ASAP ou NIGHT';
   COMMENT ON COLUMN "VBS_DIFFUSION"."SITE_CDE" IS 'Site Cde';
   COMMENT ON COLUMN "VBS_DIFFUSION"."DFU_LOG_GRP_IDE" IS 'Id de la diffusion';
   COMMENT ON COLUMN "VBS_DIFFUSION"."MGT_CDE" IS 'code environnement section 100 colonne 1';
   COMMENT ON COLUMN "VBS_DIFFUSION"."OLD_DIFFUSION" IS 'id de la diffusion parent si il y a eu un split de la diffusion d origine du a des limitation de taille ou de piece jointe';
   COMMENT ON COLUMN "VBS_DIFFUSION"."SPLIT_INDEX" IS 'Index du split pour cette diffusion (si une diffusion ne respect pas les contraintes syst¿me on splite la diffusion)';
   COMMENT ON COLUMN "VBS_DIFFUSION"."SPLIT_TOTAL" IS 'nombre Total de split';
