##
## Unless required by applicable law or agreed to in writing, software
## distributed under the License is distributed on an "AS IS" BASIS,
## WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
## See the License for the specific language governing permissions and
## limitations under the License.
##
$output.java($entity.repository)##

#if ($entity.hasUniqueBigIntegerAttribute())
$output.require("java.math.BigInteger")##
#end
#if ($entity.hasUniqueDateAttribute() || $entity.root.hasDatePk())
$output.require("java.util.Date")##
#end
$output.require($entity.model)##
$output.require($entity.root.primaryKey)##
#foreach ($enumAttribute in $entity.uniqueEnumAttributes.list)
$output.require($enumAttribute)##
#end
$output.require("org.springframework.data.jpa.repository.*")##

/**
 * $entity repository.
 * 
 * @author generated by Celerio
 *
 */
public interface $output.currentClass extends JpaRepository<$entity.model.type, $entity.root.primaryKey.type> {

## --------------- One to One
#foreach ($oneToOne in $entity.oneToOne.list)
$output.require("java.util.List")##
$output.require("${oneToOne.to.getPackageName()}.$oneToOne.to.type")##
	/**
	 * Find by $oneToOne.to.varUp (One To One relation).
	 */
	List<$entity.model.type> findBy${oneToOne.to.varUp}($oneToOne.to.type $oneToOne.to.var);
	
#end	
	
## --------------- Many to One
#foreach ($manyToOne in $entity.manyToOne.list)
$output.require("java.util.List")##
$output.require("${manyToOne.to.getPackageName()}.$manyToOne.to.type")##
	/**
	 * Find by $manyToOne.to.varUp (Many To One relation).
	 */
	List<$entity.model.type> findBy${manyToOne.to.varUp}($manyToOne.to.type $manyToOne.to.var);
	
#end

#if ($entity.model.type == "Book")
$output.require("org.springframework.data.repository.query.Param")##
$output.require("java.math.BigDecimal")##
	@Query("SELECT b FROM Book b WHERE LOWER(b.title) LIKE LOWER(:title) OR LOWER(b.description) LIKE LOWER(:description) OR b.price = :price")
	public List<Book> search(@Param("title") String title, @Param("description") String description, @Param("price") BigDecimal price);
#end
}